### ISSUE TITLE
Running on windows error

### ISSUE THREAD

**Issue by ngavrish** [tzutalin/adb-event-record#2]
I am trying to run it on Windows machine, because I have CAN device to work with, and I get following:

Python 3.6 

python adbrecord.py --show
Traceback (most recent call last):
  File "adbrecord.py", line 177, in <module>
    main(*sys.argv)
  File "adbrecord.py", line 153, in main
    adb_recorder.listAllEvent()
  File "adbrecord.py", line 52, in listAllEvent
    adb = subprocess.Popen(self.adb_shell_command + [b'getevent', '-i'], stdin=PIPE, stdout=PIPE, stderr=PIPE)
  File "C:\Users\build-windows\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\build-windows\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 964, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\build-windows\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

**Comment by tzutalin** [comment]
Sorry, I have not tested it on windows. Do you resolve it?

**Comment by cornelg7** [comment]
I solved this by running the script with python 2.7.
First install python 2.7, then replace the first line in the script with #!c:\[Path to python 2.7]\python.exe
